FROM golang:1.24.0-alpine3.21

WORKDIR /merch-shop

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY internal/ ./internal
COPY migrations/ ./migrations

ENV CGO_ENABLED=1