FROM golang:1.23.5 AS build-stage

WORKDIR /merch-shop

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY internal/ ./internal
COPY migrations/ ./migrations
COPY test/ ./test

CMD go test -race ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html